name: carbmin-lecture
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11.*
  - livereload==2.6.3
  # IPython and Jupyter
  - ipython
  - jupyter
  - nbqa
  # Fatiando tools
  - pooch
  - boule
  - ensaio
  - verde
  - harmonica
  # Scientific stack
  - pygmt
  - xarray
  - numpy
  - tqdm
  - rioxarray
  - pandas
